name: Integration Test
on:
    push:
      branches:
        - main
    workflow_dispatch:
        branches: [ main ]  

env:
  workflow_env_var1: workflow env 1
  workflow_env_var2: workflow env 2

jobs:
  build:
    env:
      job_env_var1: job env 1

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Self test
        id: selftest

        env:
          step_env_var1: step env 11
          step_env_var2: step env 22

        # Put your action repo here
        uses: briegel0/go_show_env_action@main
        with: 
           showGithubVars: 'true'
           listOfAppEnvVars: 'workflow_env_var1,workflow_env_var2,job_env_var1,step_env_var1,step_env_var2'

      - name: Show outputs
        run: |
          echo " output ${{ steps.selftest.outputs.myOutput}}"
 
      - name: Check ok outputs ( if does not contain expected fail... )
        if: contains(steps.selftest.outputs.myOutput, 'workflow_env_var1=workflow env 1') == false
        run: |
          exit(-1)               

      - name: Check bad outputs ( if contains unexpected, fail.... )            
        if: contains(steps.selftest.outputs.myOutput, 'workflow_env_var1=workflow env 12')
        run: |
          exit(-1)               
